# Generated by Django 3.0.4 on 2020-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('appending', 'Appending'), ('active', 'Active'), ('declined', 'Declined'), ('deleted', 'Deleted')], default='active', max_length=9)),
            ],
            options={
                'db_table': 'school_classrooms',
            },
        ),
    ]
