# Generated by Django 3.0.4 on 2020-03-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('appending', 'Appending'), ('declined', 'Declined'), ('deleted', 'Deleted')], default='active', max_length=9)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'school_lessons',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('appending', 'Appending'), ('declined', 'Declined'), ('deleted', 'Deleted')], default='appending', max_length=9)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='school.ClassRoom')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started', to='lesson.Lesson')),
                ('students', models.ManyToManyField(limit_choices_to={'status': 'active', 'type': 'student'}, related_name='lessons', to='user.User')),
                ('teacher', models.ForeignKey(limit_choices_to={'status': 'active', 'type': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, to='user.User')),
            ],
            options={
                'db_table': 'school_timetables',
            },
        ),
    ]
